### PR TITLE
chore: add label "app" from pod to logs

### PR DESCRIPTION
**Pull request by frankbaumfalk**

### CODE REVIEW

**Review by argoyle — CHANGES_REQUESTED** [review]
I think you have to run `kubectl kustomize . -o grafana-agent.yaml --enable-helm` and add the generated file as well. Should have thought of that when we spoke earlier. Sorry!

**Comment by frankbaumfalk** [comment]
No worries.
The run will upgrade the grafana-agent (not the operator) image from v0.26.1 to v0.28.0 as well, should be fine.


From: Joakim Olsson ***@***.***>
Date: Wednesday, 21 December 2022 at 15:58
To: opzkit/terraform-aws-k8s-addons-grafana-agent-operator ***@***.***>
Cc: Frank Baumfalk ***@***.***>, Author ***@***.***>
Subject: Re: [opzkit/terraform-aws-k8s-addons-grafana-agent-operator] chore: add label "app" from pod to logs (PR #9)

@argoyle requested changes on this pull request.

I think you have to run kubectl kustomize . -o grafana-agent.yaml --enable-helm and add the generated file as well. Should have thought of that when we spoke earlier. Sorry!

**Comment by argoyle** [comment]
> No worries. The run will upgrade the grafana-agent (not the operator) image from v0.26.1 to v0.28.0 as well, should be fine.

Hmmm, are you sure about that? We have specified a specific version of the helm chart I think. Unless they have updated the helm-chart for that specific version I wouldn't expect a new version of the agent.

If the version changes I would prefer another PR with just the version-update and merge that one before this PR.

**Comment by frankbaumfalk** [comment]
That was output of the run with kubectl.
Old:
image: grafana/agent:v0.26.1

App versoion :
appVersion: 0.28.0

And this has not changed.
So, it sound “logical” some way with 0.28.0
We can “downgrade” it manually but I would assume that the version should be 0.28 anyway

From: Joakim Olsson ***@***.***>
Date: Wednesday, 21 December 2022 at 16:28
To: opzkit/terraform-aws-k8s-addons-grafana-agent-operator ***@***.***>
Cc: Frank Baumfalk ***@***.***>, Author ***@***.***>
Subject: Re: [opzkit/terraform-aws-k8s-addons-grafana-agent-operator] chore: add label "app" from pod to logs (PR #9)

No worries. The run will upgrade the grafana-agent (not the operator) image from v0.26.1 to v0.28.0 as well, should be fine.

Hmmm, are you sure about that? We have specified a specific version of the helm chart I think. Unless they have updated the helm-chart for that specific version I wouldn't expect a new version of the agent.

If the version changes I would prefer another PR with just the version-update and merge that one before this PR.

**Comment by argoyle** [comment]
Just ran it locally and you're correct. I'll update and add as a separate PR.

**Comment by argoyle** [comment]
Done. See what happens if you push your changes now.

**Comment by argoyle** [comment]
You still have to kubectl kustomize though

**Comment by frankbaumfalk** [comment]
Now it should be ok.

From: Joakim Olsson ***@***.***>
Date: Wednesday, 21 December 2022 at 17:47
To: opzkit/terraform-aws-k8s-addons-grafana-agent-operator ***@***.***>
Cc: Frank Baumfalk ***@***.***>, Author ***@***.***>
Subject: Re: [opzkit/terraform-aws-k8s-addons-grafana-agent-operator] chore: add label "app" from pod to logs (PR #9)

You still have to kubectl kustomize though

**Review by argoyle — APPROVED** [review]
🎖️ 🚀

**Comment by argoyle** [comment]
Baah, build doesn't run on PR's. Bummer. Will merge anyway and tag a new release shortly.

**Pull request merged**
